compile:amd64:
  stage: build
  tags:
  - amd64
  before_script:
  - if [[ ! -s /usr/include/seccomp.h ]]; then
      apt-get -q update;
      apt-get -y install libseccomp-dev libseccomp2;
    fi
  - sed -i
      -e "/^add_executable/s@signify@signify~$(dpkg --print-architecture)@"
      -e "/^TARGET_LINK_LIBRARIES/s@signify@signify~$(dpkg --print-architecture)@"
      CMakeLists.txt
  script:
  - mkdir -p build
  - cd build/
  - if [[ "$(dpkg --print-architecture)" == "amd64" ]]; then
      env CFLAGS="-Os -march=westmere -mtune=intel" cmake ..;
    else
      env CFLAGS="-Os" cmake ..;
    fi
  - make |& grep -v -F "libcurl"
  - mv signify~* ../
  - cd ..
  - file signify~*
  - ldd signify~*
  artifacts:
    expire_in: 1 week
    paths:
    - signify~*

test:
  stage: test
  image: blitznote/debootstrap-amd64:16.04
  script:
  - test/runner.sh ./signify~$(dpkg --print-architecture)

bundle_deb:amd64:
  stage: deploy
  tags:
  - amd64
  script:
  - export VERSION="$(git describe | cut -d '-' -f 1)-$(git describe | cut -d '-' -f 2)bn"
  - mkdir -p .release/{DEBIAN,usr/bin,usr/share/man/man1}
  - cp -a --reflink=auto signify~$(dpkg --print-architecture) .release/usr/bin/signify
  - cat signify.1 | bzip2 -9c >.release/usr/share/man/man1/signify.1.bz2
  - cp -a debian/* .release/DEBIAN/
  - sed -i
      -e "/^Version/c\Version\x3a ${VERSION}"
      -e "/^Architecture/c\Architecture\x3a $(dpkg --print-architecture)"
      -e "/^Installed-Size/c\Installed-Size\x3a $(du -s .release/usr | cut -f 1)"
      .release/DEBIAN/control
  - dpkg-deb -z9 -Zxz --build .release "signify-linux_${VERSION}_$(dpkg --print-architecture).deb"
  artifacts:
    expire_in: 1 week
    paths:
    - "*deb"
