default:
  image: 'ubuntu:18.04'

compile:
  stage: build
  before_script:
  - apt-get -q update
  - apt-get -y --no-install-recommends --allow-downgrades --fix-broken install \
      gcc cmake ninja-build pkg-config \
      libc6-dev libseccomp-dev libseccomp2 \
      curl
  script:
  - mkdir -p build
  - cd build/
  - env CFLAGS="-Os" cmake -GNinja ..
  - ninja
  - mv signify ../
  artifacts:
    expire_in: 1 week
    paths:
    - signify

test:
  stage: test
  script:
  - test/runner.sh ./signify

bundle_deb:
  stage: deploy
  before_script:
  - apt-get -q update
  - apt-get -y --no-install-recommends --allow-downgrades --fix-broken install \
      dpkg xz-utils bzip2
  script:
  - export VERSION="$(head -n 1 src/signify.c | cut -d ' ' -f 4)"
  - mkdir -p .release/{DEBIAN,usr/bin,usr/share/man/man1}
  - mv signify .release/usr/bin/
  - cat signify.1 | bzip2 -9c >.release/usr/share/man/man1/signify.1.bz2
  - cp -a debian/* .release/DEBIAN/
  - sed -i
      -e "/^Version/c\Version\x3a ${VERSION}"
      -e "/^Architecture/c\Architecture\x3a $(dpkg --print-architecture)"
      -e "/^Installed-Size/c\Installed-Size\x3a $(du -s .release/usr | cut -f 1)"
      .release/DEBIAN/control
  - dpkg-deb -z9 -Zxz --build .release "signify-linux_${VERSION}_$(dpkg --print-architecture).deb"
  artifacts:
    expire_in: 1 week
    paths:
    - "*deb"
